<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/Sumi.ico</ApplicationIcon>
    <AssemblyName>Sumi</AssemblyName>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../Sumi.Core/Sumi.Core.csproj" /></ItemGroup>
  <ItemGroup><Using Remove="System.Windows.Forms" /><Using Remove="System.Drawing" /></ItemGroup>
  <ItemGroup><None Include="../../LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" /></ItemGroup>
  <ItemGroup><Resource Include="Assets/Sumi.ico" /></ItemGroup>
</Project>
